Не срабатывает создание процессов.
Застревает в моменте создания процессов.
Поэтому следует продебажить часть создания тасков. Сейчас не создаётся процесс при создании процесса.
Причина оказалась в том, что файловый дескриптор был закрыт. Из-за этого не создавался процесс.
Поэтому чекаем что у нас не так функцией открытия файла в процессе создания тасок.

Последняя ошибка это
  File "/usr/local/Cellar/python@3.10/3.10.13/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 1638, in _get_handles
    c2pwrite = stdout.fileno()
ValueError: I/O operation on closed file
при создании процесса.

